name: Daily-News-ChatFlow

on:
  schedule:
    - cron: "0 16 * * *"   # 北京 00:00
  workflow_dispatch:

jobs:
  news:
    runs-on: ubuntu-latest
    env:
      BASE:  ${{ secrets.DIFY_BASE_URL }}
      TOKEN: ${{ secrets.DIFY_APP_TOKEN }}
      RSS:   ${{ secrets.RSS_LIST }}
      SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
    steps:
      - name: Call Dify ChatFlow
        id: call
        shell: bash
        run: |
          echo ">> 生成请求体"
          jq -n --arg q "请抓取以下 RSS 并分类摘要：\n${RSS}" \
                '{query:$q,inputs:{},response_mode:"blocking",conversation_id:"",user:"cron"}' \
                > body.json
          
          echo ">> 调用 /chat-messages"
          curl -sS -X POST "$BASE/chat-messages" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d @body.json > resp.json
          
          ANSWER=$(jq -r '.answer' resp.json)
          echo "::set-output name=digest::$ANSWER"
          echo "NEWS_DIGEST<<EOF" >> $GITHUB_ENV
          echo "$ANSWER"         >> $GITHUB_ENV
          echo "EOF"             >> $GITHUB_ENV

      - name: Push via ServerChan
        if: env.SERVERPUSHKEY != ''
        shell: bash
        run: |
          TITLE="每日 RSS 摘要 $(date +%F)"
          curl -sS -X POST "https://sctapi.ftqq.com/${SERVERPUSHKEY}.send" \
            -d "title=$TITLE&desp=${NEWS_DIGEST}"
